import Head from "next/head";
import Typewriter from 'react-typewriter';
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillMail
} from "react-icons/ai";
import { FaReact } from 'react-icons/fa';
import { 
  SiReact, SiAngular, SiHeroku, SiAmazonaws, SiDigitalocean, SiNodedotjs, SiNextdotjs, SiTailwindcss, SiSass, SiMysql, SiMongodb, SiPostgresql, SiMicrosoftazure, SiSwagger
} from 'react-icons/si'
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import icon from "../public/icon.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Praveen kumar Chettibilli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl bg-gradient-to-b from-violet-500 rounded-full p-2">PC</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-violet-500 text- to-violet-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="../public/New Updated Resume.pdf" download>
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-violet-600 font-medium dark:text-violet-400 md:text-6xl">
              Praveen kumar Chettibilli
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl transition-smooth">
              <Typewriter typing={1}>
                UX Designer, Photographer, Developer, Good Friend
              </Typewriter>
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            An enthusiastic Full Stack Developer with a passion for building efficient, scalable web applications. 
            With hands-on experience in Angular, .NET Core, and AWS, I enjoy solving complex problems and creating intuitive user experiences. 
            Let’s connect to turn innovative ideas into reality!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a 
      href="https://www.linkedin.com/in/praveen-kumar-chettibilli" 
      target="_blank" 
      rel="noopener noreferrer" 
    >
      <AiFillLinkedin size={50} />
    </a>
    <a 
      href="https://github.com/PraveenKumarChettibilli" 
      target="_blank" 
      rel="noopener noreferrer" 
    >
      <AiFillGithub size={50} />
    </a>
    <a 
      href="mailto:praveenkumar.chettibilli@gmail.com" 
      target="_blank" 
      rel="noopener noreferrer" 
    >
      <AiFillMail size={50} />
    </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-violet-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={icon} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="mx-auto text-center text-3xl py-10 dark:text-white ">PROJECTS</h3>
            {/* <p className="text-md leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 font-bold ">
                Personal-budget-management
              </h3>
              <p className="py-2 text-left">
              A full-stack web application with NodeJS and Angular to analyze spending and track future expenses,
              featuring interactive graphs and tables.
              </p>
              <h4 className="py-4 text-violet-600">Environment/Frameworks/Language Used</h4>
              <p className="text-gray-800 py-1">Heroku, Digital Ocean, MongoDB, Git</p>
              <p className="text-gray-800 py-1">Angular, SCSS</p>
              <p className="text-gray-800 py-1">NodeJS, D3JS</p>
              <p className="text-gray-800 py-1">TypeScript</p>
              <a href="https://github.com/PraveenKumarChettibilli/personal-budget-heroku" target="_blank" rel="noopener noreferrer" className="text-gray-800 hover:text-gray-600 transition duration-300">
                <AiFillGithub size={30} />
              </a>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 font-bold">
              Climate Data Analysis System Using MapReduce and Hive
              </h3>
              <p className="py-2 text-left">
              A robust climate data analysis system using MapReduce and Hive to process and analyze GHCNd
              historical climate data.
              </p>
              <h4 className="py-4 text-violet-600">Environment/Frameworks/Language Used</h4>
              <p className="text-gray-800 py-1">Java, Apache Hadoop, Linux</p>
              <p className="text-gray-800 py-1">Hadoop</p>
              <p className="text-gray-800 py-1">Linux</p>
              {/* <p className="text-gray-800 py-1">Indesign</p> */}
              <a href="https://github.com/PraveenKumarChettibilli" target="_blank" rel="noopener noreferrer" className="text-gray-800 hover:text-gray-600 transition duration-300">
                <AiFillGithub size={30} />
              </a>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 font-bold"> V Blog </h3>
              <p className="py-2 text-left">
              A full-stack web application for a university blog using Django and MySQL, enabling the posting of
              tech-related information and current activities.
              </p>
              <h4 className="py-4 text-violet-600">Environment/Frameworks/Language Used</h4>
              <p className="text-gray-800 py-1">MySQL, Heroku, Git</p>
              <p className="text-gray-800 py-1">Django</p>
              <p className="text-gray-800 py-1">Python</p>
              {/* <p className="text-gray-800 py-1">Indesign</p> */}
              <a href="https://github.com/PraveenKumarChettibilli" target="_blank" rel="noopener noreferrer" className="text-gray-800 hover:text-gray-600 transition duration-300">
                <AiFillGithub size={30} />
              </a>
            </div>
          </div>
          <div className="mx-auto text-right dark:text-white ">
            <a href="https://github.com/PraveenKumarChettibilli" target="_blank" rel="noopener noreferrer" className="mx-auto text-right p-2 rounded-3xl dark:text-white bg-transparent border-blue-400 border-4">
            More Projects on github---//</a>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl text-center py-1 dark:text-white ">SKILLS</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I possess a diverse set of technologies that enhance my capabilities as a developer. 
            My experience allows me to build dynamic user interfaces and deploy applications seamlessly in the cloud. 
            I utilize scalable cloud services for efficient infrastructure management and focus on creating responsive, efficient backend systems. 
            I ensure effective collaboration and project management through version control while implementing modern styling techniques for visually appealing designs. 
            Additionally, I handle data storage and management efficiently, leveraging various database solutions, 
            and enhance the development process through comprehensive API documentation.
            </p>
            <p className="text-md text-center font-extrabold py-2 leading-8 text-gray-800 dark:text-gray-200">
            These are the skills with which I am familiar:
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="flex flex-wrap justify-center items-center space-x-10 text-center space-y-10">
          <a className="text-blue-600 hover:text-blue-800">
            <SiReact size={55} /> React
          </a>
          <a className="text-red-600 hover:text-red-800">
            <SiAngular size={55} /> Angular
          </a>
          <a className="text-purple-600 hover:text-purple-800">
            <SiHeroku size={55} /> Heroku
          </a>
          <a className="text-orange-600 hover:text-orange-800">
            <SiAmazonaws size={55} /> AWS
          </a>
          <a className="text-blue-500 text-center hover:text-blue-700">
            <SiDigitalocean size={55} /> Digital Ocean
          </a>
          <a className="text-green-600 hover:text-green-800">
            <SiNodedotjs size={55} /> Node.js
          </a>
      <a className="text-black hover:text-gray-800 dark:text-white">
        <AiFillGithub size={55} /> Github
      </a>
      <a className="text-black hover:text-gray-800 dark:text-white">
        <SiNextdotjs size={55} /> next.js
      </a>
      <a className="text-blue-400 hover:text-blue-600">
        <SiTailwindcss size={55} /> Tailwindcss
      </a>
      <a className="text-pink-500 hover:text-pink-700">
        <SiSass size={55} /> SASS
      </a>
      <a className="text-blue-600 hover:text-blue-800">
        <SiMysql size={55} /> MySQL
      </a>
      <a className="text-green-600 hover:text-green-800">
        <SiMongodb size={55} /> MongoDB
      </a>
      <a className="text-blue-600 hover:text-blue-800">
        <SiPostgresql size={55} /> PostgreSQL
      </a>
      <a className="text-blue-500 hover:text-blue-700">
        <SiMicrosoftazure size={55} /> Azure
      </a>
      <a className="text-black hover:text-gray-800 dark:text-white">
        <SiSwagger size={55} /> Swagger
      </a>
          </div>
            {/* <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
